### ISSUE TITLE
Neue Seite erstellen

### ISSUE THREAD

**Issue by KipaUser** [TLoebner/tilebasedInfopages#12]
Meine Bitte an dich wäre, könntest du hinter die Kachel "Kirchen in Bonn" ebenfalls eine Kacheloptik erstellen wie hinter den Hilfeseiten (Beispiel: siehe Bild in Anlage). Es werden dann 5 neue Kacheln benötigt welche verlinkt sein sollen. 

Kachel 1 -> Evangelischer Kirchenkreis Bonn -> http://www.bonn-evangelisch.de/  
Kachel 2 -> Evangelischer Kirchenkreis Bad Godesberg-Voreifel -> http://bgv.ekir.de/ 
Kachel 3 -> Evangelischer Kirchenkreis An Sieg und Rhein -> http://www.ekasur.de/ 
Kachel 4 -> Katholische Kirche Bonn -> http://www.kath-bonn.de/?oid=15 
Kachel 5 -> Arbeitsgemeinschaft christlicher Kirchen in Bonn -> http://www.ack-bonn.de/

**Comment by TLoebner** [comment]
This will be a new app, which will be started after klicking on the button. Please specify the functions and the neccessary admin menu in more detail.

My suggestion is:
- simple tiles with links, which could be configured using the admin menu
- in admin menu, the color, text and link could be changed

Open questions:
- shape of the tiles ?
- size of the tiles ?
- are there any animations neccessary ?

Please give me some feedback on that.

**Comment by TLoebner** [comment]
will be solved with T#13
