### ISSUE TITLE
Feedback Button 

### ISSUE THREAD

**Issue by KipaUser** [TLoebner/tilebasedInfopages#4]
Das Feedback Symbol auf der Hauptseite „?“ sollte größer und erkennbarer gemacht werden.

**Comment by TLoebner** [comment]
Will be fixed in Release 1.0 in December. 

Please specify "größer" in more detail. Should there be a complete Editor in admin page collection for specify pixel or should there be a rem-based aproach be implemented ?

**Comment by TLoebner** [comment]
This Bugfix will also influence the other editable buttons in the admin interface.

**Comment by TLoebner** [comment]
this ticket is now included in T#7
